### ISSUE TITLE
What is resize doing?

### ISSUE THREAD

**Issue by twmht** [bnulihaixia/Deep_metric#15]
I can't understand the code

https://github.com/bnulihaixia/Deep_metric/blob/master/losses/Weight.py#L45

why using resize here?

**Comment by bnulihaixia** [comment]
To  get positive pairs' cosine similarities for each anchor.

**Comment by twmht** [comment]
I always got unequall element errors..

it seems that the size of the tensor should remain the same size after resize.

Any idea?

**Comment by liuxindazz** [comment]
@bnulihaixia You have done a great work, however, this resize is unreasonable. The pos_sim can be resized only if `y_ = 8*list(range(num_class))`.

**Comment by liuxindazz** [comment]
@bnulihaixia OK, I will try it.

**Comment by erobic** [comment]
@bnulihaixia If you could add comments explaining each step in the `forward()` function, I could probably modify the code to work even when the sampling is not balanced.
