### ISSUE TITLE
about weight loss

### ISSUE THREAD

**Issue by SaintLogos1234** [bnulihaixia/Deep_metric#32]
I appreciate your work very much. When I read your source code, I found that the code for weight loss was not released. May I ask when will it be released

**Comment by bnulihaixia** [comment]
I delete it due to the policy of my company. However, you can implement it according the binomial deviance loss and the paper. It is easy to implement (No more than 5 lines of code). If you have done this, you can open it.

**Comment by farbodtm** [comment]
Hi! Thanks for the great work!! would you be able to send me your paper? farbod.motlagh@adelaide.edu.au

**Comment by fiona-lxd** [comment]
> I delete it due to the policy of my company. However, you can implement it according the binomial deviance loss and the paper. It is easy to implement (No more than 5 lines of code). If you have done this, you can open it.

Could you please provide the paper name of Weight Loss? I want to cite it in my paper.
