### ISSUE TITLE
About the hyper parameters of weight loss

### ISSUE THREAD

**Issue by justyouforeverml** [bnulihaixia/Deep_metric#34]
Hey, thank you for uploading your code and sharing your work.I tried running your code, but the  result is not good as that given in your paper.At first,I thought it was a hyper parameter(alphabet and base) problem as the parameters set in the code were inconsistent with those in the paper.I tried to run the code according to the parameters in the paper, and found that the result were worse.Could mind sharing the best hyper parameters of the weight loss(alpha=?,beta=?,base=?),thank u very much!

**Comment by bnulihaixia** [comment]
In the paper, you can find the default parameter. You can reach the performance of my paper without changing these parameters.
